# Generated by Django 6.0.8 on 2026-08-22 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_user_user_papel_cooperativa_coerentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_oficial', models.BooleanField(default=False)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
            ],
            options={
                'verbose_name': 'Cenário',
                'verbose_name_plural': 'Cenários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade_estatica', models.FloatField()),
                ('capacidade_expedicao_diaria', models.FloatField()),
                ('estoque_inicial', models.FloatField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
            ],
            options={
                'verbose_name': 'Armazém',
                'verbose_name_plural': 'Armazéns',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade_estatica', models.FloatField()),
                ('capacidade_esmagamento_diaria', models.FloatField()),
                ('capacidade_recebimento_diaria', models.FloatField()),
                ('limite_caminhoes', models.IntegerField()),
                ('carga_media_caminhao', models.FloatField()),
                ('estoque_inicial', models.FloatField()),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
            ],
            options={
                'verbose_name': 'Fábrica',
                'verbose_name_plural': 'Fábricas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.FloatField()),
                ('custo_frete_ton', models.FloatField()),
                ('custo_frete_entressafra', models.FloatField(default=0)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='simulacao.armazem')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='simulacao.fabrica')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
    ]
