# Generated by Django 6.0.8 on 2026-08-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_user_papel_cooperativa_coerentes'),
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade_ton', models.FloatField()),
                ('custo_total', models.FloatField()),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.armazem')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.fabrica')),
            ],
            options={
                'verbose_name': 'Movimentação Diária',
                'verbose_name_plural': 'Movimentações Diárias',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='PrevisaoArmazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('recebimento_produtor', models.FloatField(default=0)),
                ('vendas', models.FloatField(default=0)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='simulacao.armazem')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
            ],
            options={
                'verbose_name': 'Previsão de Armazém',
                'verbose_name_plural': 'Previsões de Armazém',
            },
        ),
        migrations.CreateModel(
            name='PrevisaoFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('recebimento_produtor', models.FloatField(default=0)),
                ('vendas', models.FloatField(default=0)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='simulacao.fabrica')),
            ],
            options={
                'verbose_name': 'Previsão de Fábrica',
                'verbose_name_plural': 'Previsões de Fábrica',
            },
        ),
        migrations.CreateModel(
            name='SafraUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_tipo', models.CharField(max_length=20)),
                ('entidade_id', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
            ],
            options={
                'verbose_name': 'Safra da Unidade',
                'verbose_name_plural': 'Safras das Unidades',
            },
        ),
    ]
