# Generated by Django 6.0.8 on 2026-08-22 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_user_papel_cooperativa_coerentes'),
        ('simulacao', '0002_movimentacaodiaria_previsaoarmazem_previsaofabrica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('mensagem', models.CharField(blank=True, default='', max_length=500)),
                ('duracao_segundos', models.FloatField(blank=True, null=True)),
                ('dias_simulados', models.IntegerField(blank=True, null=True)),
                ('cenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
            ],
            options={
                'verbose_name': 'Log de Execução',
                'verbose_name_plural': 'Logs de Execução',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='ResumoMensalArmazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('rec_produtor', models.FloatField(default=0)),
                ('envio_transbordo', models.FloatField(default=0)),
                ('vendas', models.FloatField(default=0)),
                ('saldo_estoque', models.FloatField(default=0)),
                ('capacidade_estatica', models.FloatField(default=0)),
                ('excedente', models.FloatField(default=0)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.armazem')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
            ],
            options={
                'verbose_name': 'Resumo Mensal de Armazém',
                'verbose_name_plural': 'Resumos Mensais de Armazém',
            },
        ),
        migrations.CreateModel(
            name='ResumoMensalFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('rec_produtor', models.FloatField(default=0)),
                ('rec_transbordo', models.FloatField(default=0)),
                ('esmagado', models.FloatField(default=0)),
                ('saldo_estoque', models.FloatField(default=0)),
                ('capacidade_estatica', models.FloatField(default=0)),
                ('excedente', models.FloatField(default=0)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.fabrica')),
            ],
            options={
                'verbose_name': 'Resumo Mensal de Fábrica',
                'verbose_name_plural': 'Resumos Mensais de Fábrica',
            },
        ),
    ]
