# Generated by Django 6.0.8 on 2026-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_user_papel_cooperativa_coerentes'),
        ('simulacao', '0003_logexecucao_resumomensalarmazem_resumomensalfabrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cenario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cenario',
            constraint=models.UniqueConstraint(fields=('cooperativa', 'nome'), name='simulacao_cenario_unique_cooperativa_nome'),
        ),
    ]
