# Generated by Django 6.0.8 on 2026-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0004_alter_cenario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logexecucao',
            name='status',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em andamento'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='', max_length=50),
        ),
    ]
