# Generated by Django 6.0.8 on 2026-08-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_email_obrigatorio_unico'),
        ('simulacao', '0005_alter_logexecucao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('mensagens', models.JSONField(default=list)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_ia', to='simulacao.cenario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='core.cooperativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa IA',
                'verbose_name_plural': 'Conversas IA',
                'ordering': ['-updated_at'],
            },
        ),
    ]
