# Generated by Django 6.0.8 on 2026-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dias_janela_safra_padrao', models.PositiveSmallIntegerField(blank=True, help_text='Parâmetro placeholder para a janela de safra padrão da cooperativa; semântica real definida quando SafraUnidade for portado (próxima fase).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cooperativa',
                'verbose_name_plural': 'Cooperativas',
                'ordering': ['nome'],
            },
        ),
    ]
