# Generated by Django 6.0.8 on 2026-08-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cooperativa__isnull', True), ('papel', 'admin_vector')), models.Q(models.Q(('papel', 'admin_vector'), _negated=True), ('cooperativa__isnull', False)), _connector='OR'), name='user_papel_cooperativa_coerentes'),
        ),
    ]
