# Generated by Django 6.0.8 on 2026-08-28 20:25

import apps.integracoes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_user_user_papel_cooperativa_coerentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Rótulo do serviço que usa esta chave.', max_length=120)),
                ('chave', models.CharField(default=apps.integracoes.models.gerar_chave, editable=False, max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='core.cooperativa')),
            ],
            options={
                'verbose_name': 'Chave de API',
                'verbose_name_plural': 'Chaves de API',
                'ordering': ['-created_at'],
            },
        ),
    ]
